name: colmi_r0x_controller_sample_ui
description: "COLMi R0x Controller Sample UI Demo"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  colmi_r0x_controller:
    path: ../../
  flutter_blue_plus: ^1.32.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
