name: colmi_r0x_controller_raw_viewer
description: "COLMi R0x Controller Raw Viewer Demo"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  colmi_r0x_controller:
    path: ../../
  flutter_blue_plus: ^1.32.8
  oscilloscope: ^0.2.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
